1.16.2
DoctorMacc/BedrockBackwards pull request #6
Opened 2020-08-10 10:31 UTC by D3ATHBRINGER13

2020-08-10 11:00 UTC, rtm516 requested changes

2020-08-10 11:00 UTC, rtm516 commented on common/src/main/java/com/github/doctormacc/common/protocols/backwards/v408_to_v407_BackwardsPacketHandler.java
> +        return true;
Your missing a bracket before this, creating a build fail.

2020-08-10 15:18 UTC, DoctorMacc commented
Looks good! The v408 class does need to be added to the array in BedrockVersion.java, though.

2020-08-10 15:18 UTC, D3ATHBRINGER13 commented
Oh sorry, thought it done that xd

2020-08-10 15:39 UTC, DoctorMacc commented on common/src/main/java/com/github/doctormacc/common/protocols/backwards/v408_to_v407_BackwardsPacketHandler.java
> +            String entityReplacement = null;
Couldn't this be simplified to:

```java
            if (((AddEntityPacket) packet).getIdentifier().equals("minecraft:piglin_brute")) {
                ((AddEntityPacket) packet).setIdentifier("minecraft:piglin");
            }
```

2020-08-13 15:50 UTC, Camotoy approved these changes

2020-08-13 15:51 UTC, merged